[package]
name = "learning-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = { version = "*", optional = true }

rand = "0.8.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

quick-xml = "0.22.0"
